# For a direct USB cable connection, the port name is typically
# /dev/ttyACM# where is # is a number such as 0, 1, 2, etc
# For a wireless connection like XBee, the port is typically
# /dev/ttyUSB# where # is a number such as 0, 1, 2, etc.

port: /dev/ttyACM0
baud: 57600
timeout: 0.1

rate: 50
sensorstate_rate: 10

use_base_controller: True
base_controller_rate: 26

use_uarm_controller: True
uarm_controller_rate: 10

use_camera_controller: True
camera_controller_rate: 5

publish_tf: True

# === Robot drivetrain parameters
wheel_diameter: 0.067
wheel_track: 0.23
encoder_resolution: 988 # from Pololu for 131:1 motors
gear_reduction: 1.0
#motors_reversed: True

# === PID parameters
Kp: 150
#Kd:6
Kd: 0
#Ki: 400
Ki: 0
Ko: 50
#accel_limit: 9.0

# === Sensor definitions.  Examples only - edit for your robot.
#     Sensor type can be one of the follow (case sensitive!):
#	  * Ping
#	  * GP2D12
#	  * Analog
#	  * Digital
#	  * PololuMotorCurrent
#	  * PhidgetsVoltage
#	  * PhidgetsCurrent (20 Amp, DC)



sensors: {
  robot_voltage:   {pin: 1, type: CustomVoltage, rate: 1},
  robot_current:   {pin: 2, type: CustomCurrent, rate: 1},
  motor_current_right:  {pin: 3, type: CustomMotorCurrent, rate: 1},
  motor_current_left:   {pin: 4, type: CustomMotorCurrent, rate: 1},
  #ir_front_center:      {pin: 2, type: GP2D12, rate: 10},
  #sonar_front_center:   {pin: 5, type: Ping, rate: 10},
  sonar_front_left:   {pin: 45, type: PointCloudPing, rate: 1, frame_id: /base_fl_sonar_link},
  sonar_front_middle_left:   {pin: 47, type: PointCloudPing, rate: 1, frame_id: /base_fml_sonar_link},
  sonar_front_center:   {pin: 49, type: PointCloudPing, rate: 1, frame_id: /base_fc_sonar_link},
  sonar_front_middle_right:   {pin: 51, type: PointCloudPing, rate: 1, frame_id: /base_fmr_sonar_link},
  sonar_front_right:   {pin: 53, type: PointCloudPing, rate: 1, frame_id: /base_fr_sonar_link},
  arduino_led:          {pin: 13, type: Digital, rate: 1, direction: output}
}
